version: "3"

services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - "$POSTGRES_PORT:5432"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_TYPE: postgres
      DB_HOST: 188.120.224.251
      DB_PORT: 9012 #Internal PG port
      DB_USER: master_wiki_js
      DB_PASS: PcCe=v_HmkA65gtKJpzuUE
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data:
